### ISSUE TITLE
Wiki Vervollständigen

### ISSUE THREAD

**Issue by Amatetzu** [Amatetzu/Rezept-Management-System#2]
**Who is Assigned:** @Amatetzu  @soyasoe 

**Description of tasks to be completed:**
Vervolständige das Wiki für dieses Projekt um eine gute Übersicht zu erhalten

**Special considerations:**
- wie werden Daten gespeichert
- Mit was wir arbeiten
- wie soll die gui außehen
- ...
**Deadline:** 29.06.2024

**Comment by Amatetzu** [comment]
Datenspeicherung hinzugefügt

**Comment by soyasoe** [comment]
erster Grober entwurf GUI wurde hinzugefügt
