### ISSUE TITLE
Erstellen Beispiel für Zutatenliste

### ISSUE THREAD

**Issue by soyasoe** [Amatetzu/Rezept-Management-System#3]
**Who is Assigned:**
@soyasoe 

**Description of tasks to be completed:**
Erstelle eine JSON-datei mit Beispieldaten für Zutaten
**Special considerations:**
Folgendes Format muss eingehalten werden:

```json
[
  {
    "Name": "Butter",
    "Einheit": "g",
    "Menge": 500.0,
    "Allergene": [
      "lactose"
    ],
    "EnergieKcal": 717.0,
    "Kategorie": [
      "Tierisches Produkt",
      "Vegetarisch"
    ]
  },
  {
    "Name": "Eier",
    "Einheit": "Stück",
    "Menge": 10.0,
    "Allergene": [
      "Ei"
    ],
    "EnergieKcal": 155.0,
    "Kategorie": [
      "Tierisches Produkt",
      "Vegetarisch"
    ]
  }
]

```

**Deadline:**
29.06.2024

**Comment by soyasoe** [comment]
json datei mit Beispielcode wurde erstellt, zusätlicher Hinweis dass das Format eingehalten werden muss ist gegeben wurden

**Comment by Amatetzu** [comment]
es wäre besser wenn da noch ein paar mehr Zutaten eingefügt werden, aber dass muss auch nicht mehr heute passieren

**Comment by soyasoe** [comment]
hab noch ein paar Zuten hinzugefügt, Grundgerüst an Zutaten sollte definitiv gegeben sein @Amatetzu kannst ja noch mal schauen ob dir auf anhieb da noch was einfällt oder erst mal so ausreicht
